version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - './src:/application'
            - dbdata:/var/lib/mysql
            - './scripts/init.sql:/docker-entrypoint-initdb.d/1.sql'
            - './scripts/classicmodels.sql:/docker-entrypoint-initdb.d/2.sql'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - '3002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './src:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '3000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './src:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        env_file:
            - ".env"

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql
        ports:
            - '8080:80'
volumes:
    dbdata: